name: Build Flutter App

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App Version'
        type: string
        required: false

jobs:
  flutter-build-relase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'
      - run: flutter --version
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: build apk
        run: flutter build apk --split-per-abi
      - name: upload release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'build/app/outputs/flutter-apk/*.apk'
          tags: true
          draft: false
          tag_name: ${{ inputs.version }}
      - name: node set
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: build web
        run: |
          flutter build web --web-renderer html --release
          node bin/optiweb.js
          cp -rf build/app/intermediates/assets/release/mergeReleaseAssets/flutter_assets/fonts build/web/assets
          ls build/web
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.KEY }}
          source: "build/web/*"
          target: "web/app/"
          rm: true
      - run: echo 'success deployed'